### ISSUE TITLE
No detections with peopleSegNetv2 on Jetson TX2

### ISSUE THREAD

**Issue by Edu4444** [NVIDIA-AI-IOT/deepstream_tao_apps#40]
Hello. I have tested peopleSegNetv2 con a jetson nano and it's working as expected, but on a jetson TX2 the network is not generating any detection over the input image.  Threre are no output labels using SHOW_MASK=1 or SHOW_MASK=0. Other models are working fine, I have tested SSD succesfully.

Jetpack 4.5.1,Deepstream 5.1, TensorRT 7.1.3, TRT OSS plugin built with -DGPU_ARCHS="62".
Using latest github files.

```
mero-jetson@Jetson-TX2:~/deepstream_tlt_apps$ export SHOW_MASK=1
mero-jetson@Jetson-TX2:~/deepstream_tlt_apps$ ./apps/tlt_detection/ds-tlt-detection -c configs/peopleSegNet_tlt/pgie_peopleSegNetv2_tlt_config.txt -i /opt/nvidia/deepstream/deepstream-5.1/samples/streams/sample_720p.jpg
```

Output image:
![out](https://user-images.githubusercontent.com/42138754/124906176-118fac80-dfe7-11eb-8747-a8a04cafdce6.jpg)

**Comment by younglalala** [comment]
Hello,Has this problem been solved？

**Comment by Edu4444** [comment]
Hello. 
Unfortunately it has not been solved yet.

**Comment by younglalala** [comment]
Hello,I have solved the problem.Do not convert the model to INT8, conversion to FP16 will work
