### ISSUE TITLE
gstnvtracker: Unable to acquire a user meta buffer. Try increasing user-meta-pool-size

### ISSUE THREAD

**Issue by emad555** [NVIDIA-AI-IOT/deepstream_tao_apps#89]
I am getting this in the terminal when I run:
sudo ./deepstream-mdx-perception-app  -c ../../../configs/app/retail_object_detection_recognition.yml

gstnvtracker: Unable to acquire a user meta buffer. Try increasing user-meta-pool-size

**Comment by emad555** [comment]
solved by changing the sink type.

**Comment by sperezs95** [comment]
> solved by changing the sink type.

Hello, I am having this same problem with my deepstream application, my application uses a yolov8 model and as output it has an RTSP stream, set g_object_set (G_OBJECT (sink), "type", 4, NULL); but the error continues, could you help me where exactly I should change the sink type?
